services:
  chatbotui:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-ui:v1
    container_name: chatbot
    environment:
      NEXT_PUBLIC_SUPABASE_URL: http://supabase_kong_chatbotui:8000
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    ports:
      - '3001:3001'
    networks:
      - chatbot-ui-network


networks:
  chatbot-ui-network:
    external:
      name: supabase_network_chatbotui